### ISSUE TITLE
Missing imported .less file content on compile

### ISSUE THREAD

**Issue by kevinlieser** [babobski/Komodo-LESS-Compiler#5]
I am trying to compile bootstrap.less files. Within the main bootstrap.less there are many other imported LESS files. One of them is `@import "panels.less";`. But after compiling the CSS file I am missing the content of panels.css and one or two other files.

An example is attached. Unzip it, open bootstrap.less and try to compile. My not compressed CSS file gets 99.249 Bytes and is missing anything with class ".panel".

Using Komodo 10.1.4 on macOS Sierra.

[example.zip](https://github.com/babobski/Komodo-LESS-Compiler/files/688247/example.zip)

**Comment by babobski** [comment]
@kevinlieser Thanks for the report, found out what is the problem. The addon should strip out the commented imports, but noticed it stripes out more than that.

**Comment by babobski** [comment]
@kevinlieser the bug is fixed in the [latest release](https://github.com/babobski/Komodo-LESS-Compiler/releases/latest). ( for FireFox you need to save link as or else it tries to import it in FireFox. Than drag and drop the .xpi in to install/update the addon  )

**Comment by kevinlieser** [comment]
Wow, that was lightning fast! Thanks for your support!

**Comment by babobski** [comment]
No problem, glad to help 👍
